### ISSUE TITLE
JDK8:  java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by melloware** [overview/mime-types#10]
Running with JDK8.  Works fine with JDK11

```
Exception in thread "Thread-14" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
        at org.overviewproject.mime_types.MimeTypeDetector$2.completed(MimeTypeDetector.java:299)
        at org.overviewproject.mime_types.MimeTypeDetector$2.completed(MimeTypeDetector.java:294)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:281)
        at sun.nio.ch.WindowsAsynchronousFileChannelImpl$ReadTask.completed(WindowsAsynchronousFileChannelImpl.java:491)
        at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:397)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T11:06:16-04:00)
Maven home: C:\Tools\apache-maven-3.6.2
Java version: 1.8.0_211, vendor: Oracle Corporation, runtime: C:\Tools\jdk1.8.0_211\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by melloware** [comment]
Looks similar to: https://github.com/apache/felix/pull/114

**Comment by adamhooper** [comment]
Thanks for the report! I have a fix. Sonatype isn't letting me release right now; I'll try again after lunch.

**Comment by adamhooper** [comment]
The release finally went through. Please try out v1.0.1.

**Comment by melloware** [comment]
Cool I just switched our tests from Tika to MimeTypes 1.0.1 in JDK8, 11, 15 and all is passing: https://github.com/primefaces/primefaces/pull/6624
